### PR TITLE
Support for PUT and DELETE

### PR DESCRIPTION
**Pull request by odynvolk**

### CODE REVIEW

**Review by lilianjap — APPROVED** [review]
🚮 🏆 🍏

**Review by esvalberg — APPROVED** [review]
✺◟( ͡° ͜ʖ ͡°)◞✺ yay! ✺◟( ͡° ͜ʖ ͡°)◞✺

**Review by RudqwistLucas — APPROVED** [review]
🤙 🤙

**Review by jonaswalden — APPROVED** [review]
great scott! :tung:

**Pull request merged**
